version: '3.8'
services:
  back:
    build:
      context: 'backend'
      target: dev
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
  front:
    build:
      context: './frontend'
      target: dev
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    depends_on:
      - back
