version: '3.8'

services:
  frontend:
    extends:
      file: docker-compose.base.yml
      service: turbo-app-base
    command: yarn dev:front
    ports:
      - 3000:3000
  backend:
    extends:
      file: docker-compose.base.yml
      service: turbo-app-base
    command: yarn dev:back
    ports:
      - 4000:4000
  db:
    image: mysql:9.1
    platform: linux/x86_64
    command: mysqld
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
volumes:
  mono-node-modules:
  db-data:
