version: '3.8'
services:
  back:
    build:
      context: 'backend'
      target: production
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
    depends_on:
      - db
  front:
    build:
      context: 'frontend'
      target: production
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    depends_on:
      - back
  db:
    image: mysql:8.0
    command: mysqld
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
